### PR TITLE
Initial migration of maven-shaded-log4j-transformer

### PR DESCRIPTION
**Pull request by edwgiz**
Hello @ppkarwasz 

Basically  I moved the changes by the past PR, the maven build is succussfull with followind command
```
mvn --projects log4j-transform-maven-shade-plugin-extensions clean verify
```

the open question for me is how to gracefully adapt documentation which is in `log4j-transform-maven-shade-plugin-extensions/src/site/markdown/index.md`

Looking for your feedback

### CODE REVIEW

**Review by ppkarwasz — APPROVED** [review]
Hi @edwgiz,

Thank you for adapting [ PR logging-log4j-tools#2](https://github.com/apache/logging-log4j-tools/pull/2) so fast.

Although I didn't set up Github Actions on this repo yet, I run the tests locally and it looks good to me.

@vy: how should we organize the documentation?

@jvz: do we need a contributor agreement?

**Comment by vy** [comment]
For the documentation, I suggest simply using a `README.adoc` at the module folder and linking to that in the root `README.adoc` – I have done this in [log4j-tools](/apache/logging-log4j-tools). In the Log4j manual, we can simply link to the project repo, i.e., `https://github.com/apache/logging-log4j-transform`, which greets users with the root `README.adoc`. This can be a good temporary workaround until I complete my work on setting up Antora.

@edwgiz, has already signed the ICLA – search for _"Eduard Gizatullin"_ in `private@logging.apache.org` archives.

**Comment by ppkarwasz** [comment]
@edwgiz,

Thank again for the contribution. We plan to release the artifacts in this repo shortly after `2.20.0`.

**Comment by jvz** [comment]
And ICLAs are primarily required for committers anyways.

**Pull request merged**
